// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (id, title, author, published_date, isbn, collection_id, created_at, updated_at, library_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW(),
    $6
)
RETURNING id, title, author, published_date, isbn, library_id, created_at, updated_at, collection_id
`

type CreateBookParams struct {
	Title         string
	Author        string
	PublishedDate sql.NullTime
	Isbn          sql.NullString
	CollectionID  uuid.NullUUID
	LibraryID     uuid.UUID
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.PublishedDate,
		arg.Isbn,
		arg.CollectionID,
		arg.LibraryID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.PublishedDate,
		&i.Isbn,
		&i.LibraryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CollectionID,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
UPDATE collections
SET book_count = book_count - 1
WHERE id = (SELECT b.collection_id FROM books b WHERE b.id = $1)
`

func (q *Queries) DeleteBook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBook, id)
	return err
}

const getAllBooksFromCollection = `-- name: GetAllBooksFromCollection :many
SELECT id, title, author, published_date, isbn, library_id, created_at, updated_at, collection_id FROM books
WHERE collection_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllBooksFromCollection(ctx context.Context, collectionID uuid.NullUUID) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, getAllBooksFromCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.PublishedDate,
			&i.Isbn,
			&i.LibraryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CollectionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, title, author, published_date, isbn, library_id, created_at, updated_at, collection_id FROM books
WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.PublishedDate,
		&i.Isbn,
		&i.LibraryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CollectionID,
	)
	return i, err
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET title = $2,
    author = $3,
    published_date = $4,
    isbn = $5,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, author, published_date, isbn, library_id, created_at, updated_at, collection_id
`

type UpdateBookParams struct {
	ID            uuid.UUID
	Title         string
	Author        string
	PublishedDate sql.NullTime
	Isbn          sql.NullString
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.PublishedDate,
		arg.Isbn,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.PublishedDate,
		&i.Isbn,
		&i.LibraryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CollectionID,
	)
	return i, err
}
