// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (id, name, description, created_at, updated_at, library_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOW(),
    NOW(),
    $3
)
RETURNING id, name, description, book_count, created_at, updated_at, library_id
`

type CreateCollectionParams struct {
	Name        string
	Description sql.NullString
	LibraryID   uuid.UUID
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection, arg.Name, arg.Description, arg.LibraryID)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BookCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LibraryID,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections
WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, id)
	return err
}

const getAllCollectionsFromLibrary = `-- name: GetAllCollectionsFromLibrary :many
SELECT id, name, description, book_count, created_at, updated_at, library_id FROM collections
WHERE library_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetAllCollectionsFromLibrary(ctx context.Context, libraryID uuid.UUID) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, getAllCollectionsFromLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.BookCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LibraryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, name, description, book_count, created_at, updated_at, library_id FROM collections
WHERE id = $1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id uuid.UUID) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BookCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LibraryID,
	)
	return i, err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections
SET name = $2,
    description = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, description, book_count, created_at, updated_at, library_id
`

type UpdateCollectionParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, updateCollection, arg.ID, arg.Name, arg.Description)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.BookCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LibraryID,
	)
	return i, err
}
