// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: library.sql

package database

import (
	"context"
	"database/sql"
)

const createLibrary = `-- name: CreateLibrary :one
INSERT INTO library (name, description)
VALUES ($1, $2)
RETURNING id, name, description, created_at, updated_at
`

type CreateLibraryParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateLibrary(ctx context.Context, arg CreateLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, createLibrary, arg.Name, arg.Description)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLibraryByID = `-- name: GetLibraryByID :one
SELECT id, name, description, created_at, updated_at FROM library
WHERE id = $1
`

func (q *Queries) GetLibraryByID(ctx context.Context, id int32) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibraryByID, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
