// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans (id, lender, borrower, book, lent_at)
VALUES (
    $1, 
    $2, 
    $3, 
    $4, 
    NOW()
) 
RETURNING id, lender, borrower, book, lent_at, returned_at
`

type CreateLoanParams struct {
	ID       uuid.UUID
	Lender   uuid.UUID
	Borrower string
	Book     uuid.UUID
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRowContext(ctx, createLoan,
		arg.ID,
		arg.Lender,
		arg.Borrower,
		arg.Book,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.Lender,
		&i.Borrower,
		&i.Book,
		&i.LentAt,
		&i.ReturnedAt,
	)
	return i, err
}

const getLoanHistory = `-- name: GetLoanHistory :many
SELECT id, lender, borrower, book, lent_at, returned_at
FROM loans
WHERE book = $1
ORDER BY lent_at DESC
`

func (q *Queries) GetLoanHistory(ctx context.Context, book uuid.UUID) ([]Loan, error) {
	rows, err := q.db.QueryContext(ctx, getLoanHistory, book)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Loan
	for rows.Next() {
		var i Loan
		if err := rows.Scan(
			&i.ID,
			&i.Lender,
			&i.Borrower,
			&i.Book,
			&i.LentAt,
			&i.ReturnedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnLoan = `-- name: ReturnLoan :one
UPDATE loans
SET returned_at = NOW()
WHERE book = $1
RETURNING id, lender, borrower, book, lent_at, returned_at
`

func (q *Queries) ReturnLoan(ctx context.Context, book uuid.UUID) (Loan, error) {
	row := q.db.QueryRowContext(ctx, returnLoan, book)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.Lender,
		&i.Borrower,
		&i.Book,
		&i.LentAt,
		&i.ReturnedAt,
	)
	return i, err
}
