// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID            uuid.UUID
	Title         string
	Author        string
	PublishedDate sql.NullTime
	Isbn          sql.NullString
	LibraryID     uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CollectionID  uuid.NullUUID
}

type Collection struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	BookCount   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LibraryID   uuid.UUID
}

type Library struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CollectionCount int32
}
