// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Book struct {
	ID            uuid.UUID
	Title         string
	Author        string
	PublishedDate sql.NullTime
	Isbn          sql.NullString
	LibraryID     uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	CollectionID  uuid.NullUUID
	IsAvailable   bool
	Borrower      sql.NullString
}

type Collection struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	BookCount   int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LibraryID   uuid.UUID
}

type Library struct {
	ID              uuid.UUID
	Name            string
	Description     sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
	CollectionCount int32
	UserID          uuid.UUID
}

type Loan struct {
	ID         uuid.UUID
	Lender     uuid.UUID
	Borrower   string
	Book       uuid.UUID
	LentAt     time.Time
	ReturnedAt sql.NullTime
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
