// Create a new library
POST http://localhost:8080/api/libraries
Content-Type: application/json

{
  "name": "Another Library",
  "description": "This is the library of Kalshiev"
}

####
// Get all libraries
GET http://localhost:8080/api/libraries
####
// Get a specific library by ID (replace {id} with the actual library ID)
GET http://localhost:8080/api/libraries/dbc58034-11f7-4122-a8b2-9cfb018a6a41
####
// Update a library (replace {id} with the actual library ID)
PATCH http://localhost:8080/api/libraries/67af466e-6d2e-457d-82fa-d0c21607d2f9
Content-Type: application/json 

{
  "name": "Updated Library Name",
  "description": "Updated description for the library"
}
####
// DELETE a library (replace {id} with the actual library ID)
DELETE http://localhost:8080/api/libraries/dbc58034-11f7-4122-a8b2-9cfb018a6a41
####

// Create a new collection
POST http://localhost:8080/api/collections
Content-Type: application/json

{
  "name": "Another Distinct Collection",
  "description": "This is the collection of Kalshiev",
  "library_id": "a1bdf2c9-1719-4e2e-ab20-a40a91d4bdf3"
}
####
// Get all collections
GET http://localhost:8080/api/collections
####
// Get all collections in libray (replace {library_id} with the actual library ID)
GET http://localhost:8080/api/collections?library_id=164aa250-9393-44d0-8c1e-cbcd3f7e4a6b
####
// update a collection (replace {id} with the actual collection ID)
PATCH http://localhost:8080/api/collections/4cdeb3ef-080d-4878-9969-0670764ee4f8
Content-Type: application/json

{
  "name": "Updated Collection Name",
  "description": "Updated description for the collection"
}
####
// RESET SYSTEM (delete all libraries)
POST http://localhost:8080/admin/reset