-- +goose up
CREATE TABLE IF NOT EXISTS loans (
    id UUID PRIMARY KEY,
    lender UUID NOT NULL,
    borrower TEXT NOT NULL,
    book UUID NOT NULL,
    lent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    returned_at TIMESTAMPTZ,
    FOREIGN KEY (lender) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (book) REFERENCES books(id) ON DELETE CASCADE
);

ALTER TABLE books
ADD COLUMN IF NOT EXISTS is_available BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS borrower TEXT DEFAULT NULL;

-- +goose down
DROP TABLE IF EXISTS loans;
ALTER TABLE books
DROP COLUMN IF EXISTS is_available,
DROP COLUMN IF EXISTS borrower;