
// Create a new collection
POST http://localhost:8080/api/collections
Content-Type: application/json

{
  "name": "A Collection",
  "description": "This is the collection of Kalshiev",
  "library_id": "8c9f6906-7946-415e-868a-30ce26b4e3ca"
}
####
// Get all collections
GET http://localhost:8080/api/collections
####
// Get all collections in libray (replace {library_id} with the actual library ID)
GET http://localhost:8080/api/collections?library_id=164aa250-9393-44d0-8c1e-cbcd3f7e4a6b
####
// update a collection (replace {id} with the actual collection ID)
PATCH http://localhost:8080/api/collections/4cdeb3ef-080d-4878-9969-0670764ee4f8
Content-Type: application/json

{
  "name": "Updated Collection Name",
  "description": "Updated description for the collection"
}
####