// Create a new collection
POST http://localhost:8080/api/libraries/d152f19f-1fd9-455e-83c8-3ef71fefe18a/collections
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsdWNpZW4tYWNjZXNzIiwic3ViIjoiMjVmN2Y0N2MtOWNjZS00MDIxLTk4YjQtYjJiMWJiZGQyYzgyIiwiZXhwIjoxNzgwMTcxMTk2LCJpYXQiOjE3ODAxNjc1OTZ9.k-6qrLDo1yUk4KTsB1GoMeBUbGc8O0Ntyg1GMMF_r-s

{
  "name": "Philosophy Books",
  "description": "This is the collection of Kalshiev"
}
####
// Get all collections in a library
GET http://localhost:8080/api/libraries/d152f19f-1fd9-455e-83c8-3ef71fefe18a/collections
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsdWNpZW4tYWNjZXNzIiwic3ViIjoiMjVmN2Y0N2MtOWNjZS00MDIxLTk4YjQtYjJiMWJiZGQyYzgyIiwiZXhwIjoxNzgwMTcxMTk2LCJpYXQiOjE3ODAxNjc1OTZ9.k-6qrLDo1yUk4KTsB1GoMeBUbGc8O0Ntyg1GMMF_r-s

####
// Get a specific collection by ID
GET http://localhost:8080/api/libraries/d152f19f-1fd9-455e-83c8-3ef71fefe18a/collections/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsdWNpZW4tYWNjZXNzIiwic3ViIjoiMjVmN2Y0N2MtOWNjZS00MDIxLTk4YjQtYjJiMWJiZGQyYzgyIiwiZXhwIjoxNzgwMTTcxMTk2LCJpYXQiOjE3ODAxNjc1OTZ9.k-6qrLDo1yUk4KTsB1GoMeBUbGc8O0Ntyg1GMMF_r-s

####
// Update a collection
PUT http://localhost:8080/api/libraries/d152f19f-1fd9-455e-83c8-3ef71fefe18a/collections/1
Content-Type: application/json

{
  "name": "Updated Philosophy Books",
  "description": "This is the updated collection of Kalshiev"
}
####
// Delete a collection
DELETE http://localhost:8080/api/libraries/d152f19f-1fd9-455e-83c8-3ef71fefe18a/collections/1
####
// Get all books in a collection
GET http://localhost:8080/api/libraries/d152f19f-1fd9-455e-83c8-3ef71fefe18a/collections/9438b175-c957-44b9-90f0-f5aadb3489e3/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsdWNpZW4tYWNjZXNzIiwic3ViIjoiMjVmN2Y0N2MtOWNjZS00MDIxLTk4YjQtYjJiMWJiZGQyYzgyIiwiZXhwIjoxNzgwMTcxMTk2LCJpYXQiOjE3ODAxNjc1OTZ9.k-6qrLDo1yUk4KTsB1GoMeBUbGc8O0Ntyg1GMMF_r-s

####
// Add a book to a collection
PATCH http://localhost:8080/api/libraries/d152f19f-1fd9-455e-83c8-3ef71fefe18a/collections/9438b175-c957-44b9-90f0-f5aadb3489e3/books/3c709d3b-68a1-4e79-b19b-88c575a4edb0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsdWNpZW4tYWNjZXNzIiwic3ViIjoiMjVmN2Y0N2MtOWNjZS00MDIxLTk4YjQtYjJiMWJiZGQyYzgyIiwiZXhwIjoxNzgwMTcxMTk2LCJpYXQiOjE3ODAxNjc1OTZ9.k-6qrLDo1yUk4KTsB1GoMeBUbGc8O0Ntyg1GMMF_r-s
####