// Create a new collection
POST http://localhost:8080/api/libraries/717a63ce-5428-44a9-89d8-e9e139d0984f/collections
Content-Type: application/json

{
  "name": "Philosophy Books",
  "description": "This is the collection of Kalshiev"
}
####
// Get all collections in a library
GET http://localhost:8080/api/libraries/717a63ce-5428-44a9-89d8-e9e139d0984f/collections
####
// Get a specific collection by ID
GET http://localhost:8080/api/libraries/717a63ce-5428-44a9-89d8-e9e139d0984f/collections/1
####
// Update a collection
PUT http://localhost:8080/api/libraries/717a63ce-5428-44a9-89d8-e9e139d0984f/collections/1
Content-Type: application/json

{
  "name": "Updated Philosophy Books",
  "description": "This is the updated collection of Kalshiev"
}
####
// Delete a collection
DELETE http://localhost:8080/api/libraries/717a63ce-5428-44a9-89d8-e9e139d0984f/collections/1
####
// Get all books in a collection
GET http://localhost:8080/api/libraries/717a63ce-5428-44a9-89d8-e9e139d0984f/collections/ce4ae9d7-8982-4c4f-a5f5-b8cae22ad867/books
####
// Add a book to a collection
PATCH http://localhost:8080/api/libraries/717a63ce-5428-44a9-89d8-e9e139d0984f/collections/ce4ae9d7-8982-4c4f-a5f5-b8cae22ad867/books/0d5d2207-fec5-4f74-a0e6-e28c09a0609f