// Create a new library
POST http://localhost:8080/api/libraries
Content-Type: application/json

{
  "name": "MyLibrary",
  "description": "This is the library of Kalshiev"
}

####
// Get a specific library by ID (replace {id} with the actual library ID)
GET http://localhost:8080/api/libraries/717a63ce-5428-44a9-89d8-e9e139d0984f
####
// Update a library (replace {id} with the actual library ID)
PATCH http://localhost:8080/api/libraries/717a63ce-5428-44a9-89d8-e9e139d0984f
Content-Type: application/json 

{
  "name": "Kalshiev's Library",
  "description": "There are many libraries but this one is mine"
}
####
// DELETE a library (replace {id} with the actual library ID)
DELETE http://localhost:8080/api/libraries/dbc58034-11f7-4122-a8b2-9cfb018a6a41