// Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "username": "testuser",
    "email": "testuser@example.com",
    "password": "testpassword"
}
####
// Login User
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "testpassword"
}